### ISSUE TITLE
If i use a "glass theme" something is wrong !!

### ISSUE THREAD

**Issue by cracyfloyd** [JamesWRC/hasti#73]
If i try to use a "Black Glass Theme" the background disappears and all items are white. See snapshot. Without glass is still working fine.

Any idea ??

without glass feature:
<img width="469" alt="Bildschirmfoto 2024-10-02 um 17 42 10" src="https://github.com/user-attachments/assets/09477d08-5a0a-42c6-8bb9-ed755b8f808f">

with glass feature:
<img width="472" alt="Bildschirmfoto 2024-10-02 um 17 42 59" src="https://github.com/user-attachments/assets/4bdf8995-a382-4fc5-a868-438946748183">

**Comment by JamesWRC** [comment]
Hi,

Sorry you’re having issues with this integration. Unfortunately I cannot assist with this, as I’m the developer of the hasti.app site, not the Black Glass Theme.

You might be able to get some assistance from the developer of the theme. Good luck, I hope you can get this working!
